build_from:
  aarch64: php:8.3-fpm-alpine
  amd64: php:8.3-fpm-alpine
  armhf: php:8.3-fpm-alpine
  armv7: php:8.3-fpm-alpine
  i386: php:8.3-fpm-alpine
labels:
  org.opencontainers.image.title: Wallos
  org.opencontainers.image.description: Open-Source Subscription Tracker for Home Assistant
  org.opencontainers.image.source: https://github.com/ellite/Wallos
  org.opencontainers.image.licenses: GPL-3.0
  org.opencontainers.image.authors: Riza Aslan
