build_from:
  armhf: bellamy/wallos:2.38.0
  armv7: bellamy/wallos:2.38.0
  aarch64: bellamy/wallos:2.38.0
  amd64: bellamy/wallos:2.38.0
  i386: bellamy/wallos:2.38.0
labels:
  io.hass.type: addon
  io.hass.name: Wallos
  io.hass.description: Open-Source Subscription Tracker
