name: Wallos
description: >-
  Wallos is a powerful, open-source, self-hostable personal subscription
  tracker designed to help you manage recurring expenses and subscriptions.
version: 2.2.5
slug: wallos
url: https://github.com/Riza-Aslan/Wallos-HA
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
init: false
ingress: true
ingress_port: 80
ingress_entry: /
panel_icon: mdi:cash-multiple
panel_title: Wallos
webui: http://[HOST]:[PORT:80]/
ports:
  80/tcp: 8282
ports_description:
  80/tcp: Wallos Web Interface
map:
  - type: data
    read_only: false
options:
  timezone: Europe/Berlin
schema:
  timezone: str
